-- /-
-- This file was generated by Aristotle.

-- Lean version: leanprover/lean4:v4.24.0
-- Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
-- This project request had uuid: f4e158ce-8a16-4c2c-8d30-f25200f354fa
-- -/

-- import Mathlib

-- open scoped BigOperators
-- open scoped Real
-- open scoped Nat
-- open scoped Classical
-- open scoped Pointwise

-- variable {α : Type*} [DecidableEq α]

-- def finsetCardTwoEquivSym2NotDiag : {s : Finset α // s.card = 2} ≃ {z : Sym2 α // ¬z.IsDiag} where
--   toFun s := ⟨(Sym2.equivMultiset α).symm ⟨s.1.val, s.2⟩,
--     by rcases s with ⟨s, hs⟩; rw [Finset.card_eq_two] at hs; aesop⟩
--   invFun z := ⟨z.1.toFinset, Sym2.card_toFinset_of_not_isDiag _ z.2⟩
--   left_inv := by
--     rintro ⟨s,hs⟩
--     rw [Finset.card_eq_two] at hs
--     obtain ⟨x, y, hxy, rfl⟩ := hs
--     ext
--     norm_num +zetaDelta at *
--     erw [Sym2.mem_iff]
--     simp [List.insert, hxy]
--   right_inv s := by
--     have h_eq : ∀ (a b : α), a ≠ b → (Sym2.mk (a, b)).toFinset = {a, b} := by aesop;
--     have h_eq' : ∀ (a : α), (Sym2.mk (a, a)).toFinset = {a} := by aesop;
--     rcases s with ⟨s, hs⟩;
--     rcases s with ⟨a, b⟩;
--     cases eq_or_ne a b <;> simp_all
--     · sorry
--     · symm
--       exact (Equiv.apply_eq_iff_eq_symm_apply (Sym2.equivMultiset α)).mp rfl
